# POST
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{
    "ID": 2,
  "title": "My First CAP Book",
  "author": "Jane Doe",
  "stock": 2
}


###PUT  http://localhost:4004/odata/v4/catalog/Books(1)
PUT http://localhost:4004/odata/v4/catalog/Books(2)
Content-Type: application/json

{
 "ID": 2,
      "title": "My First CAP Book",
      "author": "Jane Doe",
      "stock": 2222
}


#####
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{
  "ID": 1,
  "name": "J.K. Rowling",
  "country": "UK"
}